schema_version: 1

context:
  version: "0.31.5"

package:
  name: soco
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/soco/soco-${{ version }}.tar.gz
  sha256: 32655d66b832f05c58cf0ae80141e593788228b22a61048e1590487dd421e2c8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pytest
    - pip
    - setuptools >=78.1.1
  run:
    - python >=${{ python_min }}
    - requests
    - xmltodict
    - ifaddr
    - appdirs
    - lxml

tests:
  - python:
      imports:
        - soco
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: SoCo (Sonos Controller) is a simple library to control Sonos speakers.
  license: MIT
  license_file: LICENSE.rst
  homepage: https://github.com/SoCo/SoCo

extra:
  recipe-maintainers:
    - HeavyTony2
