schema_version: 1

context:
  version: "0.31.4"

package:
  name: soco
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/soco/soco-${{ version }}.tar.gz
  sha256: 00d34226dbdaf8abfca62545d9a10ed69fe13f203f0786ff5ea26bb1b9eb4e04

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pytest
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - requests
    - xmltodict
    - ifaddr
    - appdirs
    - lxml

tests:
  - python:
      imports:
        - soco
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: SoCo (Sonos Controller) is a simple library to control Sonos speakers.
  license: MIT
  license_file: LICENSE.rst
  homepage: https://github.com/SoCo/SoCo

extra:
  recipe-maintainers:
    - HeavyTony2
